apiVersion: apps/v1
kind: Deployment
metadata:
  name: orsb-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orsb-dev
  template:
    metadata:
      labels:
        app: orsb-dev
    spec:
      containers:
        - name: orsb-dev
          image: sh21202/orsb_dev:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: sr-orsb-dev