spring:
  datasource:
    url: jdbc:mysql://81shinez.iptime.org:30003/ordev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${mysql-username}
    password: ${mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.ourRestaurant.ourRestaurant
  mapper-locations: mybatis/**/*.xml
echo:
  secret:
    log:
      level=${loglevel}